tap "nikitabobko/tap"

brew "btop"
brew "coreutils"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "git"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "tree-sitter-cli"
brew "wget"

cask "nikitabobko/tap/aerospace"
cask "font-iosevka-term-nerd-font"
cask "wezterm"
