# this file should be sourced, not executed

alias v="nvim ."

if command -v gls >/dev/null 2>&1; then
  # requires coreutils on mac
  alias ls="gls -lAh --color --group-directories-first"
else
  alias ls="ls -lAhG"
fi

# git commands
alias gs="git status --short"
alias gb="git --no-pager branch"
alias gl="git log --oneline --graph --parents --all --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset' --date=short"
alias gnl="git --no-pager log --oneline --graph --parents --all --max-count=20 --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset' --date=short"
alias gcat="git cat-file -p"
alias glols="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset' --stat"
